services:
  backend:
    build: ./backend
    container_name: bmf-backend
    environment:
      - MONGO_URI=${MONGO_URI:-mongodb://mongo:27017/}
    depends_on:
      - mongo
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: bmf-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend
    networks:
      - app-network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  mongo:
    image: mongo:6
    container_name: bmf-mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: bmf-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: