version: '3.8'

services:
  # Nginx for serving frontend and proxying API
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro  # for SSL certificates if needed
    depends_on:
      - backend
    restart: unless-stopped

  # Flask backend
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - FLASK_ENV=production
    depends_on:
      - mongo
    restart: unless-stopped

  # MongoDB
  mongo:
    image: mongo:6
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data: